### ISSUE TITLE
не работает на андроид 4.1

### ISSUE THREAD

**Issue by Demenkop** [mpamop/modules_repo_mpamop#1]
уменя андроид 4.1 я пытался поставить не вышло вот посмотрите![image](https://user-images.githubusercontent.com/46030746/80845342-9461ee00-8c11-11ea-8538-c897df05ddca.jpeg)

**Comment by mpamop** [comment]
> уменя андроид 4.1 я пытался поставить не вышло вот посмотрите!

А вы попробуйте с другого браузера

**Comment by Demenkop** [comment]
спасибо заработало подпишитесь на @Demenkop
